FROM amazon/aws-cli:latest

ARG KUBECTL_VERSION
ARG TARGETARCH

RUN if [ -z "$KUBECTL_VERSION" ]; then \
        echo "KUBECTL_VERSION build argument is required." >&2; exit 1; \
    fi; \
    if [ "$TARGETARCH" = "amd64" ]; then \
        curl -L "https://github.com/k3s-io/k3s/releases/download/v${KUBECTL_VERSION}%2Bk3s1/k3s" -o /usr/local/bin/k3s; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        curl -L "https://github.com/k3s-io/k3s/releases/download/v${KUBECTL_VERSION}%2Bk3s1/k3s-arm64" -o /usr/local/bin/k3s; \
    else \
        echo "Architecture $TARGETARCH is not supported." >&2; exit 1; \
    fi; \
    chmod +x /usr/local/bin/k3s; \
    ln -s /usr/local/bin/k3s /usr/local/bin/kubectl

CMD ["/bin/sh"]